---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: trivy-operator
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://aquasecurity.github.io/helm-charts/'
    targetRevision: 0.23.3
    chart: trivy-operator
    helm:
      values: |-
        tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
        trivyOperator:
          scanJobPodTemplateContainerSecurityContext:
            runAsUser: 0
          scanJobTolerations:
            - key: "CriticalAddonsOnly"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
        trivy:
          resources:
              requests:
                cpu: 100m
                memory: 100M
              limits:
                memory: 500M
          command: filesystem
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
