---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-cert-manager
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  source:
    path: cert-manager/
    repoURL: "https://github.com/robertzd/argo-aks-k8s.git"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true